[package]
name    = "genshin_pinyin_sort"
version = "1.1.5"
edition = "2021"

[profile.release]
strip = true
lto   = true
panic = "abort"

[dependencies]
chrono = "0.4.42"

version_lib  = { path = "./version_lib" }
exchange_lib = { path = "./rename_lib", package = "name_exchanger_rs" }
sort_lib     = { path = "./sort_lib" }
